scheduled:
  sendmail:
    cron: 0 */1 * * * ?
    toAddress: 13658206101@163.com
    fromAddress: xie.bowen@ustcinfo.com
feign:
  hystrix:
    enabled: true
    timeout: 60000
  http:
    connectTimeoutMillis: 60000
    readTimeoutMillis: 60000
  platformBaseUrl: http://192.168.156.178:8080/platform
spring:
  datasource:
    crm:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000
        maximumPoolSize: 15
      url: jdbc:oracle:thin:@
      driver-class-name: oracle.jdbc.OracleDriver
      username:
      password:
      maximum-pool-size: 10
      auto-commit: true
    common:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000
        maximumPoolSize: 15
      url: jdbc:oracle:thin:@
      driver-class-name: oracle.jdbc.OracleDriver
      username:
      password:
      maximum-pool-size: 10
      auto-commit: true
    common-stat:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        maxLifetime: 1765000
        maximumPoolSize: 15
      url: jdbc:oracle:thin:@
      driver-class-name: oracle.jdbc.OracleDriver
      username:
      password:
      maximum-pool-size: 10
      auto-commit: true
  mail:
    host: mail.ustcinfo.com
    username: xie.bowen
    password: waFP26
    enable: true
    filePath: C:/Users/13658/IdeaProjects/send_mail
    properties:
      mail.mime.splitlongparameters: false
logging:
  level:
    root: debug